HansViolinWebApp/HansViolinWebApp/ViewComponents/BusinessProfileViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using HansViolinWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using HansViolinWebApp.Data;

namespace HansViolinWebApp.ViewComponents
{
    public class BusinessProfileViewComponent : ViewComponent
    {
        private readonly HansViolinWebContext _context;

        public BusinessProfileViewComponent(HansViolinWebContext context)
        {
            _context = context;
        }
        [Authorize]
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var profile = await _context.BusinessDetails.FirstOrDefaultAsync();
            if(profile == null)
            {
                profile = new BusinessDetail();
                _context.BusinessDetails.Add(profile);
                await _context.SaveChangesAsync();
            }
            return View(profile);
        }
    }
}

HansViolinWebApp/HansViolinWebApp/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using HansViolinWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using HansViolinWebApp.Data;

namespace HansViolinWebApp.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private readonly HansViolinWebContext _context;

        public CategoryListViewComponent(HansViolinWebContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _context.Categories.ToListAsync());
        }
    }
}

HansViolinWebApp/HansViolinWebApp/ViewComponents/NewsManagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using HansViolinWebApp.Models;
using HansViolinWebApp.Models.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using HansViolinWebApp.Data;

namespace HansViolinWebApp.ViewComponents
{
    public class NewsManagerViewComponent :ViewComponent
    {
        private NewsRepository newsRepository;
        public NewsManagerViewComponent (HansViolinWebContext context)
        {
            newsRepository = new NewsRepository(context);
        }

        [Authorize]
        public async Task<IViewComponentResult> InvokeAsync(bool isPublished)
        {
            if (isPublished)
            {
                return View(await newsRepository.GetAllPublishedNews());
            }
            else
            {
                return View(await newsRepository.GetAllUnPublishedNews());
            } 
        }
    }
}

HansViolinWebApp/HansViolinWebApp/Views/Admin/CreatePost.cshtml
@model HansViolinWebApp.Models.News

@{
    ViewData["Title"] = "Create Post";
    Layout = "~/Views/Shared/_admLayout.cshtml";
}

    <div id="header-bg" class="header-visible"></div>


    <div class="container title-padding">
        <h2>Create a post</h2>
        <div class="row">
            <div class="col-md-12">
                <form asp-action="CreatePost">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Content" class="control-label">HTML</label>
                        <textarea rows="30" asp-for="Content" class="form-control"></textarea>
                        <span asp-validation-for="Content" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="CreatedDate" />
                    <input type="hidden" asp-for="PublishedDate" />
                    <input type="hidden" asp-for="IsPublished" />
                    <div class="form-group d-flex justify-content-center">
                        <span class="mr-2">
                            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                        </span>
                        <span>
                            <input type="submit" value="Save & Preview" class="btn btn-primary" />

                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/EditPostTranslation.cshtml
@model HansViolinWebApp.Models.News

@{
    ViewData["Title"] = "Edit Post";
    Layout = "~/Views/Shared/_admLayout.cshtml";
}

    <div id="header-bg" class="header-visible"></div>


    <div class="container title-padding">
        <h2>修改翻译</h2>
        <div class="row">
            <div class="col-md-12">
                <form asp-action="EditPost" asp-route-id="@Model.Id">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="Title" />
                    <input type="hidden" asp-for="Content" />
                    <div class="form-group">
                        <label asp-for="TitleZh" class="control-label">标题</label>
                        <input asp-for="TitleZh" class="form-control" />
                        <span asp-validation-for="TitleZh" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContentZh" class="control-label">HTML内容</label>
                        <textarea rows="30" asp-for="ContentZh" class="form-control">@Model.ContentZh</textarea>
                        <span asp-validation-for="ContentZh" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="CreatedDate" />
                    <input type="hidden" asp-for="PublishedDate" />
                    <input type="hidden" asp-for="IsPublished" />
                    <div class="form-group d-flex justify-content-center">
                        <span class="mr-2">
                            <a asp-action="NewsPreview" asp-route-id="@Model.Id" class="btn btn-secondary">Cancel</a>
                        </span>
                        <span>
                            <input type="submit" value="Save" class="btn btn-primary" />

                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_admLayout.cshtml";
}

<div id="header-bg" class="header-visible"></div>

<div id="PlaceHolderHere"></div>

<div class="content-container container" id="admin-panel">
    <h1>Admin Panel</h1>

    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-news-tab" data-toggle="tab" href="#nav-news" role="tab" aria-controls="nav-news" aria-selected="true">News</a>
            <a class="nav-item nav-link" id="nav-instrument-tab" data-toggle="tab" href="#nav-instrument" role="tab" aria-controls="nav-instrument" aria-selected="false">Instruments</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Business Profile</a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-news" role="tabpanel" aria-labelledby="nav-news-tab">
            <ul class="nav nav-pills tag-group justify-content-center mt-2" id="pills-tab" role="tablist">
                <li class="nav-item tag-item p-0">
                    <a class="nav-link active" id="pills-publish-tab" data-toggle="pill" href="#pills-publish" role="tab" aria-controls="pills-publish" aria-selected="true">Published</a>
                </li>
                <li class="nav-item tag-item p-0">
                    <a class="nav-link" id="pills-draft-tab" data-toggle="pill" href="#pills-draft" role="tab" aria-controls="pills-draft" aria-selected="false">Draft</a>
                </li>
            </ul>
            <div class="tab-content " id="pills-tabContent">
                <a asp-controller="admin" asp-action="CreatePost" class="btn btn-small ml-4">Create New</a>

                <div class="tab-pane fade show active " id="pills-publish" role="tabpanel" aria-labelledby="pills-publish-tab">
                    <div id="news-manager-publish" class="admin-panel-container">@await Component.InvokeAsync("NewsManager", true)</div>
                </div>
                <div class="tab-pane fade " id="pills-draft" role="tabpanel" aria-labelledby="pills-draft-tab">
                    <div id="news-manager-draft" class="admin-panel-container">@await Component.InvokeAsync("NewsManager", false)</div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="nav-instrument" role="tabpanel" aria-labelledby="nav-instrument-tab">
            <div id="instrument-list" class="admin-panel-container">@await Component.InvokeAsync("CategoryList")</div>
        </div>

        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            <div id="business-profile" class="admin-panel-container">@await Component.InvokeAsync("BusinessProfile")</div>
        </div>

    </div>


</div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_CreateCategory.cshtml
@model HansViolinWebApp.Models.Category

<div class="modal fade" id="addCategory">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addCategoryLabel">Add Category</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="CreateCategory">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="CategoryName" class="control-label">Name*</label>
                                <input asp-for="CategoryName" class="form-control" />
                                <span asp-validation-for="CategoryName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PathName" class="control-label">Url Path Name*(不可更改, 全英文小写，不能有空格（用-代替））</label>
                                <input asp-for="PathName" class="form-control" />
                                <span asp-validation-for="PathName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea rows="3" asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CoverUrl" class="control-label">Cover Image Link</label>
                                <input asp-for="CoverUrl" class="form-control" />
                                <span asp-validation-for="CoverUrl" class="text-danger"></span>
                            </div>
                            *必填<br />
                            <span>Note: Categories are displayed in the order of creation!</span>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-save="modal">Add</button>
            </div>
        </div>
    </div>
</div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_CreateImage.cshtml
@model HansViolinWebApp.Models.Image

<div class="modal fade" id="addImage">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addImageLabel">Add Image</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="CreateImage">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <span>@Model.Item.ItemName</span>
                            </div>
                            <input type="hidden" asp-for="ItemId" />
                            <div class="form-group">
                                <label asp-for="Url" class="control-label">Url*</label>
                                <input asp-for="Url" class="form-control" />
                                <span asp-validation-for="Url" class="text-danger"></span>
                            </div>
                            <input type="hidden" asp-for="SequenceNumber" />
                            *Required<br />
                            <span>Note: Images are displayed in the order of creation!</span>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-save="modal">Add</button>
            </div>
        </div>
    </div>
</div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_DeleteCategory.cshtml
@model HansViolinWebApp.Models.Category

<div class="modal fade" id="deleteCategory">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="deleteCategoryLabel">Delete Category</h4>
            </div>
            <div class="modal-body">
                <div>Delete <strong>@Model.CategoryName</strong> and its instruments (including sold ones)?</div>
                <form asp-action="DeleteCategory">
                    <div class="form-group">
                        <input type="hidden" asp-for="CategoryId" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-save="modal">Delete</button>
            </div>
        </div>
    </div>
</div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_DeleteItem.cshtml
@model HansViolinWebApp.Models.Item

<div class="modal fade" id="deleteItem">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="deleteItemLabel">Delete Item</h4>
            </div>
            <div class="modal-body">
                <div>Delete <strong>@Model.ItemName</strong> and its images?</div>
                <form asp-action="DeleteItem">
                    <div class="form-group">
                        <input type="hidden" asp-for="ItemId" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-save="modal">Delete</button>
            </div>
        </div>
    </div>
</div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_DeletePost.cshtml
@model HansViolinWebApp.Models.News

    <div class="modal fade" id="deletePost">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="deletePostLabel">Delete Post</h4>
                </div>
                <div class="modal-body">
                    <div>Delete <strong>@Model.Title</strong>?</div>
                    <form asp-action="DeletePost">
                        <div class="form-group">
                            <input type="hidden" asp-for="Id" />
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" data-save="modal">Delete</button>
                </div>
            </div>
        </div>
    </div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_EditCategory.cshtml
@model HansViolinWebApp.Models.Category

<div class="modal fade" id="editCategory">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="editCategoryLabel">Edit Category</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="EditCategory" id="form-content">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="CategoryId" />
                            <input type="hidden" asp-for="CategoryNameZh" />
                            <input type="hidden" asp-for="DescriptionZh" />
                            <input type="hidden" asp-for="PathName" />

                            <div class="form-group">
                                <label asp-for="CategoryName" class="control-label">Name*</label>
                                <input asp-for="CategoryName" class="form-control" />
                                <span asp-validation-for="CategoryName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea rows="3" asp-for="Description" class="form-control">@Model.Description</textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CoverUrl" class="control-label">Cover Image Link</label>
                                <input asp-for="CoverUrl" class="form-control" />
                                <span asp-validation-for="CoverUrl" class="text-danger"></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-save="modal">Save</button>
            </div>
        </div>
    </div>
</div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_EditItem.cshtml
@model HansViolinWebApp.Models.Item

<div class="modal fade" id="editItem">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="editItemLabel">Edit Instrument</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="EditItem">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="ItemId" />
                            <input type="hidden" asp-for="CategoryId" />
                            <input type="hidden" asp-for="CoverUrl" />
                            <input type="hidden" asp-for="CoverId" />
                            <input type="hidden" asp-for="ItemNameZh" />
                            <input type="hidden" asp-for="OriginInfoZh" />
                            <input type="hidden" asp-for="DescriptionZh" />
                            <input type="hidden" asp-for="SoldinfoZh" />
                            <input type="hidden" asp-for="CategoryName" />

                            <div class="form-group">
                                <label asp-for="ItemName" class="control-label">Name</label>
                                <input asp-for="ItemName" class="form-control" />
                                <span asp-validation-for="ItemName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea rows="5" asp-for="Description" class="form-control">@Model.Description</textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PriceRange" class="control-label">Price Range</label>
                                <input asp-for="PriceRange" class="form-control" />
                                <span asp-validation-for="PriceRange" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="OriginInfo" class="control-label">Origin/Time info</label>
                                <input asp-for="OriginInfo" class="form-control" />
                                <span asp-validation-for="OriginInfo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="SoldInfo" class="control-label">Notable Sale Info</label>
                                <input asp-for="SoldInfo" class="form-control" />
                                <span asp-validation-for="SoldInfo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Status" class="control-label"></label>
                                <select asp-for="Status" class="form-control" asp-items="ViewBag.Status"></select>
                            </div>
                            <input type="hidden" asp-for="DateAdded" />
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-save="modal">Save</button>
            </div>
        </div>
    </div>
</div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_EditItemCover.cshtml
@model HansViolinWebApp.Models.Item

<div class="modal fade" id="editCover">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="editCoverLabel">Choose Cover</h4>
            </div>
            <div class="modal-body">
                <div class="text-center">Set this image as cover?</div>
                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="EditItemCover">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="ItemId" />
                            <input type="hidden" asp-for="CategoryId" />
                            <input type="hidden" asp-for="CategoryName" />
                            <input type="hidden" asp-for="ItemName" />
                            <input type="hidden" asp-for="Description" />
                            <input type="hidden" asp-for="PriceRange" />
                            <input type="hidden" asp-for="CoverId" />
                            <div class="form-group">
                                <label asp-for="CoverUrl" class="control-label">Cover Link</label>
                                <input asp-for="CoverUrl" class="form-control" />
                                <span asp-validation-for="CoverUrl" class="text-danger"></span>
                            </div>
                            <input type="hidden" asp-for="OriginInfo" />
                            <input type="hidden" asp-for="Status" />
                            <input type="hidden" asp-for="DateAdded" />
                            <input type="hidden" asp-for="ItemNameZh" />
                            <input type="hidden" asp-for="OriginInfoZh" />
                            <input type="hidden" asp-for="SoldInfo" />
                            <input type="hidden" asp-for="SoldinfoZh" />
                            <input type="hidden" asp-for="DescriptionZh" />
                        </form>
                    </divclass="col-md-12">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-save="modal">Save</button>
            </div>
        </div>
    </div>
</div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_EditItemTranslation.cshtml
@model HansViolinWebApp.Models.Item

<div class="modal fade" id="editItem">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="editItemLabel">修改乐器信息翻译</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="EditItem" asp-route-id="@Model.ItemId">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="ItemId" />
                            <input type="hidden" asp-for="CategoryId" />
                            <input type="hidden" asp-for="CategoryName" />
                            <input type="hidden" asp-for="ItemName" />
                            <input type="hidden" asp-for="OriginInfo" />
                            <input type="hidden" asp-for="Description" />
                            <input type="hidden" asp-for="PriceRange" />
                            <input type="hidden" asp-for="CoverId" />
                            <input type="hidden" asp-for="CoverUrl" />
                            <input type="hidden" asp-for="SoldInfo" />
                            <input type="hidden" asp-for="Status" />

                            <div class="form-group">
                                <label asp-for="ItemNameZh" class="control-label">中文名</label>
                                <input asp-for="ItemNameZh" class="form-control" />
                                <span asp-validation-for="ItemNameZh" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DescriptionZh" class="control-label">简介</label>
                                <textarea rows="5" asp-for="DescriptionZh" class="form-control">@Model.DescriptionZh</textarea>
                                <span asp-validation-for="DescriptionZh" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="OriginInfoZh" class="control-label">其他信息</label>
                                <input asp-for="OriginInfoZh" class="form-control" />
                                <span asp-validation-for="OriginInfoZh" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="SoldinfoZh" class="control-label">卖出信息</label>
                                <input asp-for="SoldinfoZh" class="form-control" />
                                <span asp-validation-for="SoldinfoZh" class="text-danger"></span>
                            </div>
                            <input type="hidden" asp-for="DateAdded" />
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-save="modal">Save</button>
            </div>
        </div>
    </div>
</div>

HansViolinWebApp/HansViolinWebApp/Views/Admin/_EditProfileTranslation.cshtml
@model HansViolinWebApp.Models.BusinessDetail


<div class="modal fade" id="editProfile">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="editProfileLabel">修改关于简介翻译</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="EditProfile">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="About" />
                            <input type="hidden" asp-for="ImageLink" />
                            <div class="form-group">
                                <label asp-for="AboutZh" class="control-label">关于</label>
                                <textarea rows="15" asp-for="AboutZh" class="form-control">@Model.AboutZh</textarea>
                                <span asp-validation-for="AboutZh" class="text-danger"></span>
                            </div>
                            <input type="hidden" asp-for="Phone" />
                            <input type="hidden" asp-for="Email" />
                            <input type="hidden" asp-for="Address" />
                            <input type="hidden" asp-for="Postcode" />
                            <input type="hidden" asp-for="Twitter" />
                            <input type="hidden" asp-for="Facebook" />
                            <input type="hidden" asp-for="Instagram" />
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-save="modal">Save</button>
            </div>
        </div>
    </div>
</div>