HansViolinWebApp/HansViolinWebApp/ViewComponents/ItemListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using HansViolinWebApp.Models;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using HansViolinWebApp.Data;

namespace HansViolinWebApp.ViewComponents
{
    public class ItemListViewComponent: ViewComponent
    {
        private readonly HansViolinWebContext _context;

        public ItemListViewComponent(HansViolinWebContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IViewComponentResult> InvokeAsync(int? categoryId)
        {
            ViewData["Category"] = categoryId;
            return View(await _context.Items.Where(c => c.CategoryId == categoryId).Include(i=>i.Images).ToListAsync());
        }
    }
}

HansViolinWebApp/HansViolinWebApp/Views/Shared/Components/CategoryList/Default.cshtml
@model IEnumerable<HansViolinWebApp.Models.Category>

    <div class="py-3">
        <div class="text-center" style="color:red"><strong>请按照展示顺序添加新分类</strong></div>
        <div class="text-center"><strong>主网页展示顺序:</strong> Categories - 最早创建的显示在菜单最上面 &#8195; Instruments - 最新创建的显示在前 &#8195; Images - 最早创建的显示在前</div>
        <div class="text-center"><strong>乐器左竖条颜色含义:</strong> Active - Purple &#8195; Notable Sales - Red &#8195; Draft - Gray</div>
    </div>

<button type="button" class="btn-secondary big-button" data-toggle="ajax-modal" data-target="#addCategory"
        data-url="@Url.Action("CreateCategory")">
    Add New Category
</button>

<div class="accordion" id="categoryList">
    @foreach (var category in Model)
    {
        <div class="card">
            <div class="card-header" id="@category.CategoryName">
                <div class="container-title">
                    <img class="header-image" src=@category.CoverUrl />
                    <button class="btn btn-link admin-card-header" type="button" data-toggle="collapse" data-target="#category-@category.CategoryId" aria-expanded="false" aria-controls="category-@category.CategoryId">
                        @category.CategoryName  @category.CategoryNameZh
                    </button>
                    <div class="container-action">
                        <button type="button" class="btn-small" data-toggle="ajax-modal" data-target="#editCategoryTranslation"
                                data-url="@Url.Action($"EditCategoryTranslation/{category.CategoryId}")">
                            翻译
                        </button>
                        <button type="button" class="btn-small" data-toggle="ajax-modal" data-target="#editCategory"
                                data-url="@Url.Action($"EditCategory/{category.CategoryId}")">
                            编辑
                        </button>
                        <button type="button" class="btn-small" data-toggle="ajax-modal" data-target="#deleteCategory"
                                data-url="@Url.Action($"DeleteCategory/{category.CategoryId}")">
                            删除
                        </button>
                    </div>
                </div>
            </div>

            <div id="category-@category.CategoryId" class="collapse show" aria-labelledby="@category.CategoryName" data-parent="#categoryList">
                <div class="card-body">
                    <div class="category-container">
                        <div class="admin-sub-container newline-wrapper">
                            <div>@category.Description</div>
                            <div>@category.DescriptionZh</div>
                        </div>
                        @await Component.InvokeAsync("ItemList", category.CategoryId)
                    </div>
                </div>
            </div>
        </div>

    }
</div>